export const TASKS_REQUEST = "TASKS_REQUEST"
export const TASKS_SUCCESS = "TASKS_SUCCESS"
export const TASKS_FAILURE = "TASKS_FAILURE"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"



